---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    # kind: GitRepository
    kind: Bucket
    name: lk8s-bucket
  path: ./apps
  prune: true
  wait: true
  timeout: 5m0s
...
