---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    # kind: GitRepository
    kind: Bucket
    name: lk8s-bucket
  path: ./infrastructure
  prune: true
...
