---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: whoami
  namespace: external-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: example-sync
  dataFrom:
  - extract:
      key: secret/whoami
...
