---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: http://vault:8200
      path: secret
      version: v2
      auth:
        # Authenticate against Vault using a Kubernetes ServiceAccount
        # https://www.vaultproject.io/docs/auth/kubernetes
        kubernetes:
          mountPath: kubernetes
          role: k8s-role
...
