---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault
  namespace: vault
spec:
  selector:
    matchLabels:
      app: vault
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
...
