---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: whoami
  namespace: external-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: whoami
  dataFrom:
  - extract:
      key: secret/whoami
...
