---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend-global
spec:
  provider:
    vault:
      server2: http://vault.vault.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        # Authenticate against Vault using a Kubernetes ServiceAccount
        # https://www.vaultproject.io/docs/auth/kubernetes
        kubernetes:
          mountPath: kubernetes
          role: k8s-role
...
