---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
  labels:
    app: minio
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /var/lib/rancher/k3s/storage/minio
...
