---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: apps
spec:
  selector:
    matchLabels:
      app: minio
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
...
