---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-db
  namespace: apps
spec:
  selector:
    matchLabels:
      app: wordpress-db
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
...
