---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
  allow-snippet-annotations: 'true'
  ssl-redirect: 'false'
...
