---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /var/lib/rancher/k3s/storage/wordpress
...
